### ISSUE TITLE
Having random outages - exited: worker (terminated by SIGKILL)

### ISSUE THREAD

**Issue by darklow** [andrewgodwin/daphne#14]
I am having outages for random delays of 1-5 minutes and can't get any more debug info than following.
I am using one daphne process and few runworker processes.

The problem is there is not enough info about reason why worker was suddenly terminated.
I am using Sentry to catch all python exceptions and when one appears usually i receive it on Sentry dashboard, but in this case, there is no error, just these lines in the log file:

Is there anyway to get more info about these cases?
I tried enabling more verbosity, but it didn't help either.
```
127.0.0.1:40726 -2016-06-04 01:00:05,450 INFO exited: worker (terminated by SIGKILL; not expected)
2016-06-04 01:00:06,458 INFO spawned: 'worker' with pid 456
2016-06-04 01:00:07,460 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-03 20:00:08,958 - INFO - runworker - Running worker against channel layer default (asgi_redis.RedisChannelLayer)
```
These are sequential rows from consolidate log - both `daphne` and `./manage.py runworker` logs to same output. Looks like `runworker` uses date with timezone by Django, while daphne doesn't, that why time differ.

I am running daphne and workers using supervisor on docker containers on Amazon ECS, which makes debugging little more complicated too:
```ini
[program:daphne]
command = daphne thirtysec.asgi:channel_layer -b 0.0.0.0 -p 8000 -v2

[program:worker]
command = python manage.py runworker -v3
```

**Comment by darklow** [comment]
Apparently these lines in log file are generated from supervisor.
Any ideas who or why could initiate SIGKILL for runworker?

**Comment by darklow** [comment]
I just read this info from Daphne docs:
http://channels.readthedocs.io/en/latest/deploying.html#run-worker-servers

> Make sure you keep an eye on how busy your workers are; if they get overloaded, requests will take longer and longer to return as the messages queue up (until the expiry or capacity limit is reached, at which point HTTP connections will start dropping).

> In a more complex project, you won’t want all your channels being served by the same workers, especially if you have long-running tasks (if you serve them from the same workers as HTTP requests, there’s a chance long-running tasks could block up all the workers and delay responding to HTTP requests).

Looks like it could be the case because of similar "symptoms", I am receiving outage notification few times a day and then it automatically gets back in 1-5 minutes, however the project is not so popular and there is no high load at all.

I am running whole project with 1 daphne instance and 2 runworker instances (each on different docker container and different ec2). I never reach even close to high load and there is plenty of free memory available.

Any way to detect and look more into what could cause workers to get overloaded, not responding and eventually killed and restarted by supervisor?
Thank you.

**Comment by darklow** [comment]
Sorry, this was supposed to be posted in channels issues, not here.

**Comment by andrewgodwin** [comment]
Did you open this in the Channels issues too? I can't see it.

**Comment by darklow** [comment]
I haven't yet, i am still monitoring and want to get more detailed debug information to understand what is happening and before I post.

**Comment by vaisaghvt** [comment]
@darklow any chance you remember how this was resolved or what was causing it?

**Comment by aditya-rewari-cb** [comment]
@darklow @vaisaghvt Did either of you got a resolution to this... I am stuck with same issue !!!
