### ISSUE TITLE
start daphne as a system task

### ISSUE THREAD

**Issue by nunesvictor** [andrewgodwin/daphne#26]
Hi,

I'm tring to start daphne as a system task on ubuntu, like uWSGI because I'm serving the application via nginx and uWSGI, but I can't start daphne without enable the virtualenv. How can I deploy my project knowing I have severals other projects in the same nginx server?

By the way, in case I need to use daphne to more then one application, is there a way to start more then one worker at once? (like uWSGI emperor mode)

**Comment by andrewgodwin** [comment]
You can run daphne from the virtualenv - such as you might do with gunicorn; just point at the binary inside the virtualenv's `bin` directory. Alternately, you could statically configure the channel backends and not import them from Django, letting you use Daphne on a system level, but that's not recommended.

Daphne doesn't have an emperor mode as the workers are already separate - the Daphne process literally only handles HTTP processing and no business logic. If you really want to run multiple ones, just launch more than one on different ports and load balance across them.
