### ISSUE TITLE
Twisted 16.3 appears to never call onMessage in Websocket protocol

### ISSUE THREAD

**Issue by andrewgodwin** [andrewgodwin/daphne#31]
The symptom is that the `websocket.receive` channel never gets anything sent to it when people send in websocket frames.

What's happening as far as Daphne is concerned is that onMessage never gets called on the WebsocketProtocol class. I've tested on Python 2 and 3 and both aren't working. Reverting to 16.2 fixes it, so I've pinned Daphne to that for now in the latest patch release while this is investigated.

**Comment by andrewgodwin** [comment]
Verified that Autobahn itself works fine by running the echo server on 16.3, so it's something in daphne.

**Comment by AlexejStukov** [comment]
The new version of twisted (16.3.1) fixed the issue for me. Maybe this can be closed?

**Comment by andrewgodwin** [comment]
When I get a working dev laptop I will verify and remove the pin if true :)

**Comment by imaurer** [comment]
FYI - Daphne on Twisted 16.2.0 works for us. But fails on 16.3.1 and 16.3.2 for us.

Ping me if you need more details. We are reverting Twisted back to 16.2.0 for now.

**Comment by andrewgodwin** [comment]
I have also verified that Twisted 16.3.2 does not fix this, so leaving the pin in place.

@AlexejStukov Could you say what versions of `autobahn` and `daphne` you have installed? Would like to know how it's working for you.

**Comment by bpeschier** [comment]
Ran into this issue today while picking up a side-project and wondered why I left it broken. Turns out updating dependencies is not as harmless as I thought :-)

Running channels 0.17.2, daphne 0.14.3 and autobahn 0.16.0

Twisted 16.2.0 runs fine, 16.3.0 and above (up to todays current, which is 16.4.0) do not.

**Comment by bpeschier** [comment]
This took some digging.

Twisted 16.3 implemented some changes to the http handling, one of which is shutting down (pausing) the producer when all content is thought to be received.

If my reasoning is correct, we only need to resume the producer after we handled the upgrade in ```process()``` of ```WebRequest```. Seems to work in 16.2 and up.

**Comment by andrewgodwin** [comment]
OK, fix finally released in daphne `0.15.0`.
