### ISSUE TITLE
Does daphne support secure connection?

### ISSUE THREAD

**Issue by faseelakv123** [andrewgodwin/daphne#35]

**Comment by andrewgodwin** [comment]
Please try to elaborate on the issue a bit more next time - the answer is not quite so simple:

* Like gunicorn and other WSGI servers, it does not support native SSL termination yet
* You can terminate SSL in front of it and make the terminator pass a header to signal Django that the request was indeed secure
* Native SSL support is coming soon, along with automatic LetsEncrypt support

**Comment by faseelakv123** [comment]
Ok. thanks @andrewgodwin . I have added a temporary fix. Please review [https://github.com/andrewgodwin/daphne/pull/36](https://github.com/andrewgodwin/daphne/pull/36)
