### ISSUE TITLE
Best # of workers: How to monitor the queue?

### ISSUE THREAD

**Issue by globophobe** [andrewgodwin/daphne#39]
Switched to Daphne behind Nginx. This morning there were many errors:

```...*5144 upstream timed out (110: Connection timed out) while reading response header from upstream...```

Would this mean that I need more workers? I have 4. I'll try increasing log verbosity and see if I can get some more information.

**Comment by andrewgodwin** [comment]
Did you configure nginx to correctly proxy WebSockets? Otherwise it'll just wait for the response headers and never get them, and you get that error.

**Comment by globophobe** [comment]
The nginx.conf is ok. Timeouts were for both HTTP and WebSocket connections. Traffic wasn't so heavy at that time. But, first for over a period of 5 minutes, and then shortly after for half an hour, the nginx's log showed 504 errors. 

In both cases, everything was 200 following the downtime.

**Comment by andrewgodwin** [comment]
I'd be interested in seeing the Daphne logs then. It should return 503 quickly when the request queue fills up rather than backlogging (channels have capacity, which we use to implement backpressure on new connections)

**Comment by globophobe** [comment]
Unfortunately, I had forgotten to include  --access-log for daphne in supervisor.conf I'll let you know if it happens again.

**Comment by kevinluvian** [comment]
@globophobe have you solved your problem? i also encountered this problem

**Comment by globophobe** [comment]
The problem didn't happen again.
